2020-03-26 23:36:08,078 INFO [root] [__init__.py(<module>:6)] - Test---------------
2020-03-26 23:36:08,441 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'a1ccb29f-98fe-4d96-a721-b0fc6538db68'}
2020-03-26 23:36:08,492 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,541 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,591 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,649 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,697 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,749 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,805 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': True, 'code': 10000, 'message': '操作成功！', 'data': '884ec266-52d2-4989-91f6-d152390d9f4e'}
2020-03-26 23:36:08,853 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,902 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
2020-03-26 23:36:08,952 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 99999, 'message': '抱歉，系统繁忙，请稍后重试！', 'data': None}
2020-03-26 23:36:09,003 INFO [root] [test_login_para.py(test01_login:27)] - 登录的结果为：{'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}
